In [1]:
import numpy as np

```
X_seen=np.load('X_seen.npy') 	(40 x N_i x D): 40 feature matrices. X_seen[i] is the N_i x D feature matrix of seen class i

Xtest=np.load('Xtest.npy')	(6180, 4096): feature matrix of the test data.

Ytest=np.load('Ytest.npy',)	(6180, 1): ground truth labels of the test data

class_attributes_seen=np.load('class_attributes_seen.npy')	(40, 85): 40x85 matrix with each row being the 85-dimensional class attribute vector of a seen class.

class_attributes_unseen=np.load('class_attributes_unseen.npy')	(10, 85): 10x85 matrix with each row being the 85-dimensional class attribute vector of an  unseen class.


```

# **METHOD 1**

In [2]:
X_seen=np.load('data/AwA_python/X_seen.npy',encoding='bytes',allow_pickle=True) #	(40 x N_i x D): 40 feature matrices. X_seen[i] is the N_i x D feature matrix of seen class i


In [7]:
for i in range(5):
    print(X_seen[i].shape)

(546, 4096)
(401, 4096)
(185, 4096)
(261, 4096)
(641, 4096)


In [11]:
# mean_0 = np.mean(X_seen[0],axis=0)
# mean_0.shape

(4096,)

In [ ]:
# Mean will store the mean of each class so shape of Mean is (40,4096,)
Mean = np.zeros((40,4096))

for i in range(40):
    Mean[i] = np.mean(X_seen[i],axis=0)
    print(Mean[i].shape)

In [10]:
print(Mean.shape)

(40, 4096)


In [11]:
Attr=np.load('data/AwA_python/class_attributes_seen.npy',encoding='bytes',allow_pickle=True) 
print(Attr.shape)

(40, 85)


In [12]:
UAttr=np.load('data/AwA_python/class_attributes_unseen.npy',encoding='bytes',allow_pickle=True) 
print(UAttr.shape)

(10, 85)


In [39]:
MAtrr = np.matmul(UAttr,Attr.T)  #MAttr is of shape (10,40) each row containg all the Sc,k without normalizing
print(MAtrr.shape)

(10, 40)


In [40]:
MAtrr = MAtrr.astype(float) #converting values to floating point before normalization
row_Sum = np.sum(MAtrr,axis=1,dtype=float) #calculation the \sum(Sc,l) for each of the 40 l'set


In [41]:
# Normalizing the values

for i in range(row_Sum.shape[0]):
    for j in range(MAtrr.shape[1]):
        MAtrr[i][j] = MAtrr[i][j]/row_Sum[i]

print("Shape of MAttr is ",MAtrr.shape)
MAtrr

Shape of MAttr is  (10, 40)


array([[0.02719407, 0.03337454, 0.02224969, 0.01359703, 0.02719407,
        0.02224969, 0.02348578, 0.02348578, 0.02348578, 0.02719407,
        0.03090235, 0.0197775 , 0.02224969, 0.02719407, 0.02843016,
        0.02348578, 0.03584672, 0.02595797, 0.02348578, 0.03090235,
        0.01606922, 0.03090235, 0.02472188, 0.02719407, 0.02472188,
        0.02224969, 0.02348578, 0.02224969, 0.02595797, 0.01606922,
        0.01730532, 0.02719407, 0.0197775 , 0.03461063, 0.02472188,
        0.02966625, 0.01606922, 0.02719407, 0.02966625, 0.02843016],
       [0.02028986, 0.02318841, 0.02463768, 0.01884058, 0.02318841,
        0.02318841, 0.02028986, 0.02173913, 0.03043478, 0.02753623,
        0.02753623, 0.01594203, 0.02463768, 0.02463768, 0.02463768,
        0.02318841, 0.02753623, 0.02898551, 0.03043478, 0.02753623,
        0.01449275, 0.02753623, 0.02753623, 0.02753623, 0.02463768,
        0.02318841, 0.02898551, 0.02898551, 0.03188406, 0.02173913,
        0.02463768, 0.02753623, 0.02463768, 0.0

In [42]:
New_row_sum = np.sum(MAtrr,axis=1,dtype=float)
np.unique(New_row_sum)

array([1., 1.])

In [17]:
# UMean will store the mean of unseen classes
# UMean = MAttr x Mean, UMean will be of shape 10,40

UMean = np.matmul(MAtrr,Mean)
UMean.shape

(10, 4096)

In [44]:
print(UMean)

[[0.00956931 0.00578741 0.00450361 ... 0.00286817 0.00362628 0.00078437]
 [0.01010446 0.00548777 0.00471963 ... 0.0029623  0.00346683 0.00076367]
 [0.01051258 0.00555565 0.00409182 ... 0.00272386 0.00339272 0.00079447]
 ...
 [0.00967957 0.0049509  0.00488979 ... 0.00304286 0.00356799 0.00068678]
 [0.00986543 0.00463587 0.00490455 ... 0.00307515 0.00357683 0.00071786]
 [0.00976548 0.00520053 0.00437291 ... 0.00294264 0.00345147 0.0008368 ]]


In [18]:
Xtest=np.load('data/AwA_python/Xtest.npy',encoding='bytes',allow_pickle=True)
Ytest=np.load('data/AwA_python/Ytest.npy',encoding='bytes',allow_pickle=True)

print("Shape of Xtest ",Xtest.shape)
print("Shape of Ytest ",Ytest.shape)

Shape of Xtest  (6180, 4096)
Shape of Ytest  (6180, 1)


In [24]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Calculate the L2 
np.linalg.norm(array1 - array2)

5.196152422706632

In [25]:

# for each x* I need to calc := (x*.T).x* + (mu_c.T).mu_c -2.(x*.T).mu_c
N = Xtest.shape[0]

print("N is ",N)

D = np.ones((N,10),dtype=float)

for i in range(N):
    xi = Xtest[i]
    for uc in range(UMean.shape[0]):
        D[i][uc] = np.linalg.norm(xi-UMean[uc])

print("Shape of D is ",D.shape)



N is  6180
Shape of D is  (6180, 10)


In [67]:
D

array([[0.849205  , 0.84718626, 0.82159414, ..., 0.85170216, 0.85358949,
        0.80269328],
       [0.85542901, 0.85433539, 0.87578524, ..., 0.83900325, 0.83775277,
        0.85959313],
       [0.80091319, 0.80100203, 0.79302459, ..., 0.81242168, 0.81098014,
        0.80303427],
       ...,
       [0.72689747, 0.72379348, 0.70842298, ..., 0.72668863, 0.72595657,
        0.69191626],
       [0.64571046, 0.64245504, 0.64150192, ..., 0.65092408, 0.65131101,
        0.65358333],
       [0.8371517 , 0.84133678, 0.86457307, ..., 0.8136665 , 0.81435309,
        0.8430163 ]])

In [43]:
Ypredicted = np.argmin(D,axis = 1) + 1

In [72]:
np.unique(Ypredicted,return_counts=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([  94,    5,  344, 2416,  421,  413,  681,  823,  861,  122]))

In [33]:
Ytrue = Ytest.reshape(-1,)
print(Ytrue.shape)
Ytrue

(6180,)


array([ 4.,  6.,  1., ..., 10.,  2.,  8.])

In [44]:
equal = (Ypredicted == Ytrue)
C = np.sum(equal)

In [31]:
Ypredicted.shape

(6180,)

In [46]:
C/N

0.46893203883495144

# **METHOD 2**